# -*- coding: utf-8 -*-
"""discretized function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14IN4H6v1Sl5sTSRkzooWUah3xDxnRCFF
"""

import cv2

imgPath = "/path/to/image"


# Reading image as an array
imgArray = cv2.imread(imgPath, cv2.IMREAD_GRAYSCALE)

# Resizing image array using interpolation
def discretize(matrix, n):
  IMG_HEIGHT = n   #Matrix dimensions in terms of n, number of discretized spaces on image
  IMG_WIDTH = n
  resizedImgArray = cv2.resize(
    imgArray, (IMG_HEIGHT, IMG_WIDTH), interpolation=cv2.INTER_AREA
  )
def findDelta(n):
  size=1
  return size/n #Luca said we should find delta in terms of a given n, and for the time being this is the formula. the size is the original size of the image.